---
# PROD.WF.Modules redeploy job parameters
name_a: MODULENAME
choices_a:
  - AbonentOrch-ear
  - AbonentUnionOrch-ear
  - AbonentUnionService-ear
  - test
name_b: HOSTNAME
choices_b:
  - allWF
  - allWF_1
  - allWF_2
  - test
name_c: HOSTNAMETEST
choices_c:
  - one
  - two
  - three
  - test
...
